### ISSUE TITLE
Multiplayer Support

### ISSUE THREAD

**Issue by utkuhalis** [MLivanos/WorldWrap#64]
Hello,

I really liked the system you created, it's just like the structure in the game https://play.eco/. However, there's something I'm really curious about. How can this system work in a multiplayer setup? When I looked at your documentation notes, it says that multiplayer support will be available in the upcoming version, but I wonder, in this setup, when two players move in different directions from the same point, how can they see each other?

Thank you, and I wish you good luck with your work.

**Comment by MLivanos** [comment]
Hello Friend,

Multiplayer is in the works and I actually do have the system working, though I need to iron out some bugs. To answer your question about how the multiplayer system works, I want to quickly reiterate how the system works in single player to simulate walking around a non-Euclidean world space. As the player moves, the world rearranges itself so the player stays relatively centered, creating the illusion of walking around a wrapping world. Non-player objects (eg NPCs, projectiles, etc) can simply be teleported from one end of the map to another to maintain this illusion in the eyes of the player.

But what if we had two (or more) players? What if they walk in opposite directions? How can we maintain the illusion for both/all of them? My solution is to create a local copy of the world for every client and treat each client as if they are playing a single player game and all of the other players are NPCs.

While the concept is simple, this takes a bit of maneuvering to pull off. The first bit is relatively straightforward - instead of instantiating objects on the network directly, I create a "WorldWrapNetworkManager" which creates local copies of each client's player object and moves them around for each player as if they were an NPC. In a regular Unity multiplayer game (using Netcode for GameObjects), the transform of a network object is put on the network such that when the transform is changed, the Euclidean position of the network object is changed for everyone on the network. For example, if client 1 moves their player from position (5, 0, 0) to (10, 0, -5), then every other client will see client 1's object move from (5, 0, 0) to (10, 0, -5). Since WorldWrap is simulating a non-Euclidean world space, these coordinates are not meaningful, so instead I create what I call a "TransformRelay", which monitors the _change_ to a transform from one frame to another and logs that change over the network. In the above example, instead of sending the position over the network, I send the _change in position_, so each client would know to move Client 1's player object by (5, 0, -5).

There is a bit more to it, namely in logging forces over the network, managing shareable resources (eg items any player can pick up), but that's the general idea: creating local copies of the world for each client, wrapping the world around for each player client-side, and logging the change in transform for each player across the network. If you'd like to check out the progress for multiplayer support, you can check out the dev branch which does have (mostly) working multiplayer but is a little rough around the edges with a few bugs I'm fixing now. Since there is interest in this, I'll add a YouTube video to demonstrate the 0.3.0-Alpha as it exists now.

Hopefully this makes sense - though I recognize that visualizing multiplayer in general is kind of tough, and this adds an extra layer of complexity to it so feel free to ask for clarification if needed.

Thanks for your interest!
-Mike

**Comment by utkuhalis** [comment]
Hello,

First of all, thank you very much for taking my message into consideration and providing this excellent explanation. I'm eagerly looking forward to the video and the new version. Best of luck with your work.

Warm regards,
Utku.

**Comment by MLivanos** [comment]
Hello Utku,

I've got my [progress video](https://www.youtube.com/watch?v=1ks5kuCNHkI) uploaded now if you'd like to take a look! Thanks for your support.
